### ISSUE TITLE
How to customize top left header

### ISSUE THREAD

**Issue by Opswatch** [forestryio/hugo-theme-novela#39] opened 2020-06-02 21:30 UTC
![Screenshot_2020-06-02 User Ops Blog](https://user-images.githubusercontent.com/15094745/83571887-9eb82600-a4f6-11ea-80f3-92506dd31a6f.png)
How do you customize the top left header? not seeing anywhere where I can change the narative themes wording.

**Comment by DirtyF** [comment] 2020-06-03 09:33
https://github.com/forestryio/hugo-theme-novela#logo

**Comment by DirtyF** [comment] 2020-06-05 11:00
Duplicate of #37

**Closed by DirtyF** 2020-06-05 11:00 UTC
Labels: duplicate
